disabled_rules:
  - opening_brace

custom_rules:
  workaround:
    included: ".*\\.swift"
    name: "Workaround"
    regex: "(?i)//\\s*WORKAROUND:"
    message: "Review whether this workaround is still required and remove it if no longer necessary."
    severity: warning
    match_kinds:
      - comment
